# backend to use for event component extraction. Currently only "ollama" is supported, but the design allows for future extension to other backends (e.g., OpenAI API, Hugging Face models, etc.)
backend: ollama
# save intermediate results every N articles to avoid data loss in case of crashes or interruptions. 
save_every: 100

extraction_config:
  model_name: "gemma3:12b"
  generation_params: # incrementar eventualmente com outros parâmetros, como max_tokens, top_p, etc.
    temperature: 0.0
    seed: 2026
    num_ctx: 4096 # é o suficente. tamanhos menores causam erros de parsing no json.