global_seed: 2026

dataset_creation:
  data_path: "/exp_local/kenzosaki/data/ai_news_dpo/" # directory to save (or load) the created dataset
  validate: true
  recreate: true # whether to recreate the dataset even if it already exists
  seed: 2026 # random seed for dataset creation and splitting

random_walks:
  bias: "none" # bias type for random walks. options: "none", "degree", "edge_weight"
  num_walks_per_node: 10
  walk_length: 5

unsloth:
  model_name: "/exp_local/kenzosaki/models/ai_events_gemma_3_4b_clm_r128_lr1e-4_no_json/best_merged" # huggingface model or a pre-trained model. it will be used as the base model for dpo alignment.
  base_model: "unsloth/gemma-3-4b-it" # to obtain the processor hf class 
  model_family: "gemma-3" # used to obtain the chat template
  max_seq_length: 1024 # input sequence length for the model
  num_proc: 8 # number of processes to use for dataset processing. if to large, it can cause memory issues. set to 1 to disable multiprocessing.
  beta: 0.1 # DPO beta parameter, controls the strength of the preference loss. Higher values make the model focus more on the preference loss.

lora:
  r: 16
  alpha: 16
  lora_dropout: 0.05
  bias: "none"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  random_state: 2026
  use_rslora: true 

training:
  loss_type: "sigmoid" # can be a list for mixed loss
  max_length: 1024 # match the unsloth max_seq_length
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  # metric_for_best_model: "eval_loss" # metric to use for early stopping and best model selection
  # eval_strategy: "steps"
  # eval_steps: 40 # evaluate every eval_steps during training
  gradient_accumulation_steps: 128 
  warmup_steps: 21
  num_train_epochs: 1 
  save_total_limit: 3 # ALSO, this parameter corresponds to the early stopping patience
  save_strategy: "steps"
  save_steps: 40 # save checkpoint every save_steps during training. 40
  learning_rate:  0.0002
  optim: "adamw_8bit"
  weight_decay: 0.001
  lr_scheduler_type: "linear"
  report_to: "none"
  output_dir: "/exp_local/kenzosaki/models/ai_events_gemma_3_4b_dpo_longer" # directory to save the fine-tuned model and results
  logging_dir: "/exp_local/kenzosaki/models/ai_events_gemma_3_4b_dpo_longer" # directory to save training logs
  seed: 2026
  data_seed: 2026
  use_liger_kernel: true # enabled to reduced peak memory usage
  remove_unused_columns: false
  torch_empty_cache_steps: 30


